# Ejercicio 9: Uso de la API de OpenAI

En este ejercicio vamos a aprender a utilizar la API de OpenAI

## 1. Uso básico

El siguiente código sirve para conectarse con la API de OpenAI de forma básica

In [1]:
from openai import OpenAI

In [4]:
OPENAI_API_KEY = ''

In [6]:
client = OpenAI(api_key=OPENAI_API_KEY)

In [7]:
response = client.responses.create(
    model="gpt-4.1",
    input="Write a one-sentence bedtime story about a unicorn."
)

print(response.output_text)

Under a silver moon, a gentle unicorn named Luna tiptoed through a field of starlight flowers, sprinkling sweet dreams wherever her sparkling hooves touched the ground.


## 2. Retrieval

### 2.1 Cargo el corpus de 20 News Groups

In [8]:
from sklearn.datasets import fetch_20newsgroups

newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))
newsgroupsdocs = newsgroups.data

In [9]:
import pandas as pd

In [22]:
newsgroups_df = pd.DataFrame(newsgroupsdocs, columns=['raw'])
newsgroups_df

raw
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             My brother is in the market for a high-performance video card that supports\nVESA local bus with 1-2MB RAM.  Does anyone have suggestions/ideas on:\n\n  - Diamond Stealth Pro Local Bus\n\n  - Orchid Farenheit 1280\n\n  - ATI Graphics Ultra Pro\n\n  - Any other high-performance VLB card\n\n\nPlease post or email.  Thank you!\n\n  - Matt\n
2      \n\n\n\n\tFinally you said what you dream about. Mediterranean???? That was new....\n\tThe area will be "greater" after some years, like your "holocaust" numbers......\n\n\n\n\n\t\t*****\n\tIs't July in USA now????? Here in Sweden it's April and still cold.\n\tOr have you changed your calendar???\n\n\n\t

### 2.2 Transformo a embeddings

In [12]:
from sentence_transformers import SentenceTransformer
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [16]:
model = SentenceTransformer('all-MiniLM-L6-v2')

C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [17]:
embeddings = model.encode(newsgroupsdocs)

In [18]:
embeddings

array([[ 0.00207798,  0.02345042,  0.02480885, ...,  0.0014359 ,
         0.0151075 ,  0.0528758 ],
       [ 0.0500603 ,  0.02698093, -0.00886483, ..., -0.0088717 ,
        -0.06737082,  0.05656359],
       [ 0.01640468,  0.08100048, -0.04953597, ..., -0.04184627,
        -0.07800218, -0.0313095 ],
       ...,
       [-0.00509084,  0.01817272,  0.04388077, ...,  0.01331368,
        -0.05997062, -0.05430663],
       [ 0.03508158, -0.05842971, -0.03385155, ..., -0.02824297,
        -0.05223113,  0.03760364],
       [-0.06498063, -0.01133726,  0.03949648, ..., -0.03573753,
         0.07217911,  0.02192114]], dtype=float32)

In [25]:
newsgroups_df['embeddings'] = embeddings.tolist()
newsgroups_df

raw  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n   
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             My brother is in the market for a high-performance video card that supports\nVESA local bus with 1-2MB RAM.  Does anyone have suggestions/ideas on:\n\n  - Diamond Stealth Pro Local Bus\n\n  - Orchid Farenheit 1280\n\n  - ATI Graphics Ultra Pro\n\n  - Any other high-performance VLB card\n\n\nPlease post or email.  Thank you!\n\n  - Matt\n   
2      \n\n\n\n\tFinally you said what you dream about. Mediterranean???? That was new....\n\tThe area will be "greater" after some years, like your "holocaust" numbers......\n\n\n\n\n\t\t*****\n\tIs't July in USA now????? Here in Sweden it's April and still cold.\n\tOr have you changed your calendar??

### 2.3 Creo una quey y hago la búsqueda

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
query = "Russian Federation"
query_emb = model.encode(query)
print(query_emb)

[-8.52377340e-03 -3.92504930e-02 -3.42000052e-02  4.32617702e-02
 -2.49907561e-03  5.95423626e-03  8.68702233e-02 -2.59020962e-02
 -6.05973997e-04 -1.71499737e-02 -7.30644912e-02 -5.86948404e-03
 -2.40230504e-02  7.72785470e-02 -8.97390172e-02 -4.86236289e-02
 -1.98789090e-02 -3.78015079e-02 -5.36042592e-03 -2.03642733e-02
 -3.16140689e-02 -9.79854167e-02  4.54782732e-02  3.91724370e-02
  5.95646948e-02  1.77145153e-02 -2.23199418e-03 -1.09468540e-02
  5.12338197e-03 -6.64867684e-02 -3.48227508e-02 -1.31535297e-02
  5.33735752e-02 -6.93239039e-03 -1.50537333e-02  1.57261379e-02
  3.70326340e-02 -5.30506037e-02  1.98961981e-03  3.04985438e-02
 -1.14550265e-02 -1.00777559e-01 -3.67123187e-02  8.75669420e-02
 -1.14588102e-03  7.48975202e-02 -2.45475583e-02  6.63253618e-03
  1.21760396e-02  1.17584644e-02  5.32353064e-04  1.13569191e-02
 -4.64758873e-02  7.52605051e-02  1.04522556e-01 -7.02960044e-02
  2.51775179e-02 -8.67980160e-03 -6.09254427e-02 -7.77300447e-02
 -6.37419149e-03 -6.61627

In [31]:
similarities = cosine_similarity(query_emb.reshape(1,-1), embeddings)

Obtengo los 5 documentos más similares a mi query

In [32]:
z = zip(newsgroups_df.raw, similarities)
sorted(z, key=lambda x: x[1], reverse=True)

[("\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n",
  array([ 0.06407066, -0.04098997,  0.1977092 , ...,  0.03166188,
          0.04120576,  0.05887027], dtype=float32))]

In [33]:
z = zip(newsgroups_df.index, similarities)
sorted(z, key=lambda x: x[1], reverse=True)

[(0,
  array([ 0.06407066, -0.04098997,  0.1977092 , ...,  0.03166188,
          0.04120576,  0.05887027], dtype=float32))]